### ISSUE TITLE
Dataset download and play 

### ISSUE THREAD

**Issue by Zoltan3057** [zdzhaoyong/GSLAM#15]
Hi there:

I download the TUM RGBD Dataset with name "rgbd_dataset_freiburg1_360.tgz"

But I cannot find .tumrgbd file on the uncompressed fold.

Dataset=<dataset_path>/rgbd_dataset_freiburg1_360/.tumrgbd

**Comment by Zoltan3057** [comment]
![screenshot from 2018-06-21 15-32-51](https://user-images.githubusercontent.com/37650678/41704323-80338126-7568-11e8-9896-e4d2d6da3b73.png)

**Comment by zdzhaoyong** [comment]
Please first download the associate tool from https://vision.in.tum.de/data/datasets/rgbd-dataset/tools and then generate the 'associate.txt" file with command:
```
associate.py $DatasetFolder/groundtruth.txt $DatasetFolder/depth.txt > tmp.txt
associate.py tmp.txt $DatasetFolder/rgb.txt > $DatasetFolder/associate.txt
rm tmp.txt
```

We don't actually need the .tumrgbd file, it is just used to identify the correct dataset plugin implementatoin. So go ahead without the file.

**Comment by Zoltan3057** [comment]
Hi, sorry for the late reply.
As you said, I generate the associate.txt file, but I still cannot open the dataset. 
![screenshot from 2018-07-02 10-14-48](https://user-images.githubusercontent.com/37650678/42142317-407f155a-7de1-11e8-9310-c46ad2dd3405.png)
![screenshot from 2018-07-02 10-15-06](https://user-images.githubusercontent.com/37650678/42142321-4225c958-7de1-11e8-8fec-af2e0d655f88.png)
![screenshot from 2018-07-02 10-17-26](https://user-images.githubusercontent.com/37650678/42142327-49f9bed2-7de1-11e8-90b7-2a1988bef5f1.png)
