### ISSUE TITLE
NPU Drone Dataset Links Not Working

### ISSUE THREAD

**Issue by pierotofy** [zdzhaoyong/GSLAM#22]
Hello :hand: I don't think this is necessary an "issue", but I just noticed that the datasets on http://zhaoyong.adv-ci.com/downloads/npu-dronemap-dataset/ which are referenced in the README can no longer be downloaded?

For example, clicking on https://pan.baidu.com/s/1gfwzcpt#path=%252FDataset%252FNPU%252FDroneMap%252Fphantom3-centralPark shows: 

![image](https://user-images.githubusercontent.com/1951843/43621167-048ffe84-96a4-11e8-84ca-6c143d919dd1.png)

Thought I'd report it. :+1:

**Comment by zdzhaoyong** [comment]
Thanks for the feedback!

**Comment by zdzhaoyong** [comment]
The old link are disabled by the driver company and I just updated the new links.
