### ISSUE TITLE
Installation in Ubuntu 16.04 - libqt4-core, dev, gui doesn't exist anymore

### ISSUE THREAD

**Issue by Keudeugi** [zdzhaoyong/GSLAM#24]
Hi, title says all.

However that packages(i.e., libqt4-**blah**) just changed its names as starting with 'libqt', and ends with '4', which should be formed as libqt**blah**4.

In other words, It would be better to change Qt installation guides from
Qt : sudo apt-get install build-essential g++ libqt4-core libqt4-dev libqt4-gui qt4-doc qt4-designer

to
Qt : sudo apt-get install build-essential g++ libqtcore4 libqtdev4 libqtgui4 qt4-doc qt4-designer

**Comment by zdzhaoyong** [comment]
Now both Qt4 and Qt5 works now.
