### ISSUE TITLE
Inconsistent paper title in the bibtex in README

### ISSUE THREAD

**Issue by cedrusx** [zdzhaoyong/GSLAM#37]
Great work!
Just found a minor inconsistency in the bibtex with your arXiv paper when I was citing it.
Suggestion:
`  title={General SLAM Framework and Benchmark},`
->
`  title={{GSLAM:} {A} General {SLAM} Framework and Benchmark},`

**Comment by cedrusx** [comment]
Also a typo in the author list:
`  author={Yong Zhao and Shibiao Xu and Shuhui Bu amd Hongkai Jiang and Pengcheng Han},`
The `amd` should be `and`.

**Comment by zdzhaoyong** [comment]
The README now is updated, thanks for your kindly advice!
