### ISSUE TITLE
Not saving trajectory file

### ISSUE THREAD

**Issue by immuhammadadil** [zdzhaoyong/GSLAM#45]
GSLAM is loading and processing frames but not showing it in panel in GUI.
It just prints the following details:
Play thread stoped.

------------------------------------  Timer report ------------------------------------
           FUNCTION                       #CALLS  MIN.T  MEAN.T  MAX.T  TOTAL 
---------------------------------------------------------------------------------------
Dataset::grabFrame                         407    1.8us  80.2ms 354.1ms  32.6 s
Main                                         1  738.5 s 738.5 s 738.5 s 738.5 s
--------------------------------- End of Timer report ---------------------------------

And not trajectory file is saved as required by Map2DFusion

**Comment by zdzhaoyong** [comment]
Trajectory can be saved with plugin metric_traj, please see: https://zdzhaoyong.github.io/GSLAM/evaluate.html
