### ISSUE TITLE
How do you save trajectory?

### ISSUE THREAD

**Issue by ryanpike96** [zdzhaoyong/GSLAM#46]
I have managed to get SVO working on some of the datasets, I was just wondering how I now use the evaluation component?

**Comment by ryanpike96** [comment]
I assume I asjust the GSLAMSVO.cpp and include the evaluation.h as a header file, but I am kind of lost from there.

**Comment by zdzhaoyong** [comment]
Now documentation is available, please update gslam and follow the documentation.
