### ISSUE TITLE
data set file

### ISSUE THREAD

**Issue by badstones** [zdzhaoyong/GSLAM#5]
Hi Zhao Yong, could you specify the dataset file, if I want to test slam system by using gslam. Thank you.

**Comment by badstones** [comment]
Thanks for your notification, but I have tried every dataset file in the folder of 'doc' and I confirm the path is correct, there is always an error that 'failed to open dataset xxx(dataset file name)', how could I fixed it? Thank you.

**Comment by zdzhaoyong** [comment]
Now you can play datasets with or without the configuration file, please update your GSLAM Version, follow the readme and try again.
