### ISSUE TITLE
请问一下各位朋友使用Euroc数据集运行gslam_orb，能出现运行界面和实时数据，看不到实时生成的地图，这个问题怎么解决呀？

### ISSUE THREAD

**Issue by 254843** [zdzhaoyong/GSLAM#53]
![11](https://user-images.githubusercontent.com/54730767/72397108-c5f59d00-3779-11ea-8707-9386c7c9fff5.png)

**Comment by baildagq** [comment]
@254843 请问这个问题已经解决了吗？如果已经解决的话，能不能描述下解决方法啊，感谢！
